ロゴを追加
sacloud/images pull request #1
Opened 2017-06-04 14:33 UTC by rotelstift

usacloudロゴの文字あり版と文字なし版を追加しました。
@yamamoto-febc ご確認いただければ幸いです。

2017-06-04 14:47 UTC, yamamoto-febc requested changes
README.mdへ著作者表示を追加した方が良いと思います。

2017-06-04 15:32 UTC, rotelstift commented
@yamamoto-febc READMEに著作者表示をしてみました。ご確認いただければ幸いです。

2017-06-04 15:41 UTC, yamamoto-febc commented on README.md
> +Author : 禎波ハヅキ
Author部分はこんな感じで個人ページへのリンクを貼ってはどうでしょうか？

Author :　[禎波ハヅキ(@rotelstift)](https://github.com/rotelstift)

2017-06-04 15:42 UTC, yamamoto-febc commented on README.md
> +Author : 禎波ハヅキ
.mdでの記述

```md
Author :　[禎波ハヅキ(@rotelstift)](https://github.com/rotelstift)
```

2017-06-04 15:49 UTC, yamamoto-febc commented on README.md
> +Author : 禎波ハヅキ
修正後は`git rebase`を実施してください。

`git rebaseの実施例`

```console
$ git rebase -i origin/master     # コミットを一つにまとめる
$ git push -f rotelstift patch-1  # -fオプションで上書きpush
```

2017-06-04 22:37 UTC, rotelstift commented on README.md
> +Author : 禎波ハヅキ
頂いたコマンドを素直に打ってみましたが、うまくコミットが一つにまとまっていない気がします。
最初のコマンドのrebaseの際に設定ファイルみたいなのが出てきて、それを初期設定のまま実行してみたのですが、そこで何かやらなければいけなかったのでしょうか？

2017-06-04 22:52 UTC, yamamoto-febc commented on README.md
> +Author : 禎波ハヅキ
`git rebase -i`の後の画面でコミットをまとめる必要があります。
こちらのページなどを参考に作業してみてください。

http://dev.classmethod.jp/tool/git/git-rebase-fixup/

2017-06-05 09:35 UTC, rotelstift commented on README.md
> +Author : 禎波ハヅキ
@yamamoto-febc ありがとうございます。無事にコミットが一つにまとまったようです。お手数をおかけしましたm(_ _)m

2017-06-05 11:51 UTC, yamamoto-febc approved these changes

2017-06-05 11:51 UTC, merged

2017-06-05 11:55 UTC, yamamoto-febc commented
@rotelstift ,

You are awesome!! Thank you!!!!!!

2017-06-05 12:01 UTC, rotelstift commented
@yamamoto-febc マージしてもらえたところ申し訳ないのですが、ロゴ有りの方でフォントがちゃんとアウトライン化されていないことに今気がつきました…。
直したらまたコミットしますので、申し訳ありませんが少々お待ちください。

2017-06-05 12:03 UTC, yamamoto-febc commented
OKです!  
別途プルリクエスト投げてください！